apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: build-and-deploy-pipelinerun
spec:
  serviceAccountName: serviceaccount
  pipelineRef:
    name: build-and-deploy
  resources:
    - name: api-repo
      resourceRef:
        name: api-repo
    - name: api-image
      resourceRef:
        name: api-image
    - name: ui-repo
      resourceRef:
        name: ui-repo
    - name: ui-image
      resourceRef:
        name: ui-image
      
          
        
          
      

        
      
        
      
        
   
            
        
    
      
        
        

          
        